### ISSUE TITLE
Previously selected date is not being selected correctly on the Time picker opening

### ISSUE THREAD

**Issue by nicolanarducci** [najlepsiwebdesigner/foundation-datepicker#137]
In the [example page](http://foundation-datepicker.peterbeno.com/example.html#time-example) when I open the Time picker the starting date is not highlighted, instead the hours and minute are correctly highlighted

**Comment by Boguslavovna** [comment]
Hi,
The same issue is interesting for me. When it will be fixed?
The selected date should be highlighted. Or maybe you know some workaround?

**Comment by mbellet** [comment]
I fixed this issue and i did a pull request, so when najlepsiwebdesigner will merge my pull this bug will be fixed.

**Comment by Boguslavovna** [comment]
Great news! Thanks a lot. Hope that merge don't take a lot of time

**Comment by najlepsiwebdesigner** [comment]
Hi! I've merged the pull request, can you please confirm it fixed the issue? I'm sorry, but I cant check it, I'm travelling in Asia. Thanks!

**Comment by Boguslavovna** [comment]
Yes, everything works fine! Bug is fixed, thank you very much :-)

**Comment by nicolanarducci** [comment]
It is still not working if the hour contains "AM" or "PM" like in us date format, and if the date is in the MM/dd/yy date format (us format).
I can upload some images if it helps

**Comment by najlepsiwebdesigner** [comment]
The 12 hour time format was never supported, sorry :(

Dňa utorok, 5. apríla 2016 nicolanarducci <notifications@github.com>
napísal(a):

> It is still not working if the hour contains "AM" or "PM" like in us date
> format, and if the date is in the MM/dd/yy date format (us format).
> I can upload some images if it helps
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/najlepsiwebdesigner/foundation-datepicker/issues/137#issuecomment-205690253>
>


-- 

Ing. Peter Beňo
--------------------------------
Web development & computer vision & robotics
http://peterbeno.com
